window.SSAGAssetIntel = (() => {
  const exact = {
    'SSAG — Strategic Systems Advisory Group': ['Umbrella operating ecosystem that packages business models, SOPs, acquisition, automation, dashboards, AI support and recurring services into reusable infrastructure.','License/setup fees, retainers, support subscriptions, royalties where legally structured, and cross-sold services.','Operating ecosystem','Consolidate live data from every production system into one owner view.'],
    'Sentinel Zero LLC': ['Cybersecurity advisory business for risk reviews, remediation planning, ongoing oversight and insurance-readiness workflows.','Assessment/advisory onboarding, monthly retainers, remediation support and referral-channel revenue.','Revenue lane','Keep acquisition, proposal, payment and service delivery connected to one CRM record.'],
    'Employee Call Dispatch Platform': ['Lets employees mark themselves on duty, distributes incoming calls across available staff and gives the owner visibility into availability, appointments and routing.','Monthly software/service fee, setup fee, or licensing to service businesses with distributed staff.','Operating system','Verify live telephony, database persistence, authentication and after-hours behavior end to end.'],
    'QuoteForge Local': ['Creates professional service quotes from a phone, calculates totals and produces customer-ready estimates.','Paid branded setup, white-label setup and recurring support.','Revenue-ready','Drive local service-business prospects into the paid setup offer.'],
    'Retail Arbitrage Business / Retail Arbitrage Command Center': ['Finds discounted or clearance products and evaluates resale opportunities so an operator can prioritize profitable inventory.','Resale profit, membership/access fees, affiliate revenue where lawful, or operator licensing.','Operating tool','Connect reliable local inventory/pricing feeds and track actual sell-through/margin.'],
    'Coupon Optimization System': ['Organizes legitimate coupons, discounts and deal combinations to lower purchase cost.','Affiliate revenue, premium access, lead generation or savings-subscription model.','Operating concept/tool','Add reliable offer feeds and validate expiration/stacking rules automatically.'],
    'AI Receptionist Business': ['Automates call answering, intake, FAQ handling, routing and appointment-oriented front-desk tasks.','Setup fee plus monthly recurring service per business/location.','Revenue lane','Complete carrier/telephony integration and package a standardized onboarding flow.'],
    'AI Calling Service': ['Provides AI-assisted outbound or inbound calling, qualification, appointment setting and follow-up where legally and technically supported.','Usage/setup fees and recurring communication-service subscriptions.','Revenue lane','Finish live calling integration, consent/compliance controls and measurable call-result reporting.'],
    'SSAG Marketplace': ['Presents turnkey businesses, operator opportunities, pricing, licensing information and application/request flows.','License/setup fees, support subscriptions, marketplace fees and lawful royalties.','Monetization platform','Only publish businesses with verified delivery, economics, support capacity and legal review.'],
    'Fintech / Payments / Wallet Business': ['Future embedded-payments layer for merchant checkout, subscriptions, reporting, wallet/card experiences and transaction services through compliant partners.','Platform subscription, transaction margin/revenue share and cross-sell retention.','Future regulated lane','Start with licensed payment rails and real merchant volume before proprietary money-transmission or token issuance.'],
    'SSAG Digital Currency / Token Concept': ['Future ecosystem payment/rewards concept intended to support transactions and loyalty once the payment layer has real usage.','Potential transaction economics and ecosystem retention only after compliant structure exists.','Future regulated lane','Do not issue first; establish payment volume, legal structure, reserves/compliance and licensed partners first.']
  };

  function capability(x){
    if (exact[x.name]) return exact[x.name];
    const n=x.name.toLowerCase(), c=x.category.toLowerCase();
    if(c.includes('position manuals')) return [`Defines the ${x.name.replace(' — Position Manual','')} role: responsibilities, authority, workflows, handoffs and performance expectations.`,`Reduces training time, mistakes and management overhead; supports faster scaling.`,`Controlled operating document`,`Link this role to its starter kit, SOPs, KPIs and current seat owner.`];
    if(c.includes('starter')) return [`Onboards and certifies the ${x.name.replace(' — Starter & Certification Kit','')} role with training steps, checklists and authorization criteria.`,`Cuts onboarding time and lowers execution errors when adding staff.`,`Controlled training asset`,`Attach proof-of-training, required systems access and release criteria.`];
    if(c.includes('workstation')) return [`Department binder consolidating procedures, controls, responsibilities and handoffs for ${x.name.replace(' — Department Workstation Binder','')}.`,`Protects continuity and allows departments to operate consistently without relying on memory.`,`Controlled operating binder`,`Keep the binder linked to current SOP versions, forms, KPIs and department owner.`];
    if(c.includes('sops')) { const a=x.name.includes('—')?x.name.split('—').slice(1).join('—').trim():x.name; return [`Step-by-step controlled procedure for ${a.toLowerCase()}, including who performs it, required handoffs and proof of completion.`,`Reduces rework, missed steps and dependence on the founder.`,`Controlled SOP`,`Attach the form/system used to execute it and a measurable completion/quality check.`]; }
    if(c.includes('forms')) { const a=x.name.includes('—')?x.name.split('—').slice(1).join('—').trim():x.name; return [`Controlled record used to document ${a.toLowerCase()} consistently.`,`Creates auditability, reduces disputes and makes operations measurable.`,`Controlled form`,`Connect this form to the SOP that requires it and the storage/retention location.`]; }
    if(c.includes('vercel')) return [`Deployed web application/version supporting ${x.name.replaceAll('_',' ')}.`,`Can support direct sales, lead capture, operations, customer delivery or internal efficiency depending on the app.`,`Deployed project`,`Confirm production route, user flow, data persistence, monetization path and current source owner.`];
    if(c.includes('github')) return [`Source-code repository preserving and controlling the codebase for ${x.name}.`,`Protects ownership, allows maintenance/deployment and increases transferable asset value.`,`Source asset`,`Map the repository to its live deployment, current branch, dependencies and operating owner.`];
    if(c.includes('top-level')){
      if(n.includes('revenue')||n.includes('funnel')) return ['Financial/funnel control system for tracking stages, conversion, cash collection and operating performance.','Improves conversion discipline and shows which revenue activities deserve more resources.','Management control','Feed it actual CRM/payment results instead of estimates.'];
      if(n.includes('command center')) return ['Owner/management workbook for tracking activation, execution, status and priorities.','Saves management time and prevents work from becoming disconnected.','Management control','Connect live system metrics and assign owners/dates to every open item.'];
      if(n.includes('manual')) return ['Controlled manual defining how a role, department or function is intended to operate.','Reduces founder dependence and makes training/replication easier.','Controlled document','Tie each section to current SOPs, systems and accountable owners.'];
      return ['Controlled enterprise document used to standardize, govern or operate part of the SSAG ecosystem.','Improves repeatability, transferability, quality control and enterprise value.','Controlled document','Keep version, owner, related systems and evidence of use attached to the record.'];
    }
    if(c.includes('standalone')){
      if(n.includes('website')) return [`Public-facing website for ${x.name.replace(' Website','')}, used to present the brand, offer and customer contact path.`,`Can generate leads or direct sales when paired with traffic, a clear offer and follow-up.`,`Customer-facing asset`,`Verify the live URL, conversion path, analytics, lead destination and follow-up automation.`];
      if(n.includes('portal')) return ['Purpose-built portal that gives a defined user group access to tools, records or workflows.','Can reduce service labor, improve retention and support recurring subscriptions.','Portal/system','Verify authentication, permissions, data persistence and the customer/employee workflow end to end.'];
      if(n.includes('dashboard')) return ['Dashboard that centralizes status, metrics, actions and links for an owner or operating team.','Saves management time and exposes bottlenecks that affect revenue.','Management system','Replace static numbers with live connected data wherever feasible.'];
      if(n.includes('crm')||n.includes('pipeline')) return ['CRM/pipeline structure for tracking leads, stages, ownership, follow-up and sales outcomes.','Directly protects revenue by preventing leads and follow-ups from being lost.','Revenue operations system','Make it the single source of truth and connect forms, calling, proposals and payments.'];
      if(n.includes('calling')) return ['Calling system covering lead queues, scripts, qualification, call status and follow-up.','Creates appointments and client opportunities from outbound/inbound calling activity.','Revenue operations system','Verify telephony, legal/compliance controls, call logging and CRM handoff.'];
      if(n.includes('arbitrage')) return ['Product-sourcing tool for identifying items that may be acquired locally and resold at a higher price.','Produces resale margin when sourcing, fees and sell-through are favorable.','Commerce tool','Use live inventory, completed-sale data and true net-margin calculations before buying.'];
      if(n.includes('legacy')||n.includes('continuity')) return ['Continuity system for organizing critical records, successor instructions and emergency operating information.','Can be sold as a service and also protects the value of the owner’s businesses.','Continuity asset','Add recurring review dates, accountable successors and secure document-storage references.'];
      return [`Recovered operating asset supporting ${x.name.toLowerCase()} within the ecosystem.`,`Value comes from direct revenue, operational savings, risk reduction or reusable intellectual property depending on how it is activated.`,`Recovered asset`,`Verify current source, live status, owner, revenue role and next dependency before calling it complete.`];
    }
    if(c.includes('businesses')) return [`Business or division model for ${x.name}; intended to package an offer, acquisition method, delivery workflow and recurring economics.`,`Potential revenue comes from its specific service/product, recurring support and cross-sell into the SSAG ecosystem.`,`Business model / venture`,`Confirm offer, pricing, customer, acquisition channel, delivery capacity and payment path before active scale.`];
    return [`Recovered SSAG asset supporting ${x.name.toLowerCase()}.`,`Its business value is revenue generation, cost/time savings, risk reduction or reusable IP.`,`Recovered asset`,`Verify source, owner, live status, dependencies and monetization role.`];
  }

  return { capability };
})();